require_relative 'ast/terminal'
require_relative 'ast/non_terminal'

require_relative 'ast/clear_stack'
require_relative 'ast/arithmetic_factory'

require_relative 'ast/assign'
require_relative 'ast/binary_add'
require_relative 'ast/binary_sub'
require_relative 'ast/binary_mult'
require_relative 'ast/binary_div'

require_relative 'ast/binary_tree_factory'
require_relative 'ast/deref'
require_relative 'ast/final'
require_relative 'ast/funcall'
require_relative 'ast/lvalue'
require_relative 'ast/nop'
require_relative 'ast/numeral'
require_relative 'ast/program_factory'
require_relative 'ast/start'
