# Rakefile - rakefile for Vish compiler/ example.vs files

require 'rake/clean'
CLEAN.include('*.vsc')

FileList['*.vs'].each do |src|
  file "#{src}c" => src
end

rule /.*\.vsc/ => '.vs' do |t|
  sh "./vishc.rb #{t.source} #{t.name}"
end

#file 'add.vsc' => 'add.vs' do |t|
#  sh "./vishc.rb #{t.prerequisites[0]} #{t.name}"   # .prerequisites}"
#end

task :default => 'add.vsc' do
  puts 'compiled .vs into .vsc'
end
