# Rakefile - rakefile for Vish compiler/ example.vs files

require 'rake/clean'
CLEAN.include('*.vsc')

require_relative 'vishc'

src_files = FileList['*.vs']

src_files.each do |src|
  file src.ext('vsc') => src
end

rule /.*\.vsc/ => '.vs' do |t|
  compiler, result = compile(compose(File.read(t.source)))
    abort("Failed to compile #{t.source}") unless result
  save(compiler, t.name)
end


desc 'compile : compiles .vs files into .vsc files'
task :compile => src_files.ext('vsc')

task :default => :compile
